[browser]
gatherUsageStats = false

[server]
runOnSave = false
fileWatcherType = "auto"
headless = true
address = "127.0.0.1"
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor = "#046A38"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#0a2e1a"
textColor = "#e6edf3"
font = "sans serif"
